// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pos33.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/33cn/chain33/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pos33Msg_Ty int32

const (
	Pos33Msg_MV Pos33Msg_Ty = 0
	Pos33Msg_BV Pos33Msg_Ty = 1
	Pos33Msg_B  Pos33Msg_Ty = 2
	Pos33Msg_MS Pos33Msg_Ty = 3
	Pos33Msg_VS Pos33Msg_Ty = 4
	Pos33Msg_CV Pos33Msg_Ty = 5
)

var Pos33Msg_Ty_name = map[int32]string{
	0: "MV",
	1: "BV",
	2: "B",
	3: "MS",
	4: "VS",
	5: "CV",
}

var Pos33Msg_Ty_value = map[string]int32{
	"MV": 0,
	"BV": 1,
	"B":  2,
	"MS": 3,
	"VS": 4,
	"CV": 5,
}

func (x Pos33Msg_Ty) String() string {
	return proto.EnumName(Pos33Msg_Ty_name, int32(x))
}

func (Pos33Msg_Ty) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{2, 0}
}

type Pos33Ticket struct {
	TicketId string `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	// 0 -> 未成熟 1 -> 可挖矿 2 -> 已挖成功 3-> 已关闭
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// genesis 创建的私钥比较特殊
	IsGenesis bool `protobuf:"varint,3,opt,name=isGenesis,proto3" json:"isGenesis,omitempty"`
	// 开启的高度
	OpenHeight int64 `protobuf:"varint,4,opt,name=openHeight,proto3" json:"openHeight,omitempty"`
	// 关闭的高度
	CloseHeight int64 `protobuf:"varint,5,opt,name=closeHeight,proto3" json:"closeHeight,omitempty"`
	//挖到的币的数目
	MinerValue   int64  `protobuf:"varint,8,opt,name=minerValue,proto3" json:"minerValue,omitempty"`
	MinerAddress string `protobuf:"bytes,6,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	// return wallet
	ReturnAddress string `protobuf:"bytes,7,opt,name=returnAddress,proto3" json:"returnAddress,omitempty"`
	// miner Price
	Price                int64    `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33Ticket) Reset()         { *m = Pos33Ticket{} }
func (m *Pos33Ticket) String() string { return proto.CompactTextString(m) }
func (*Pos33Ticket) ProtoMessage()    {}
func (*Pos33Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{0}
}

func (m *Pos33Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33Ticket.Unmarshal(m, b)
}
func (m *Pos33Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33Ticket.Marshal(b, m, deterministic)
}
func (m *Pos33Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33Ticket.Merge(m, src)
}
func (m *Pos33Ticket) XXX_Size() int {
	return xxx_messageInfo_Pos33Ticket.Size(m)
}
func (m *Pos33Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33Ticket proto.InternalMessageInfo

func (m *Pos33Ticket) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *Pos33Ticket) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Pos33Ticket) GetIsGenesis() bool {
	if m != nil {
		return m.IsGenesis
	}
	return false
}

func (m *Pos33Ticket) GetOpenHeight() int64 {
	if m != nil {
		return m.OpenHeight
	}
	return 0
}

func (m *Pos33Ticket) GetCloseHeight() int64 {
	if m != nil {
		return m.CloseHeight
	}
	return 0
}

func (m *Pos33Ticket) GetMinerValue() int64 {
	if m != nil {
		return m.MinerValue
	}
	return 0
}

func (m *Pos33Ticket) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *Pos33Ticket) GetReturnAddress() string {
	if m != nil {
		return m.ReturnAddress
	}
	return ""
}

func (m *Pos33Ticket) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// message for execs.ticket
type Pos33TicketAction struct {
	// Types that are valid to be assigned to Value:
	//	*Pos33TicketAction_Tbind
	//	*Pos33TicketAction_Topen
	//	*Pos33TicketAction_Genesis
	//	*Pos33TicketAction_Tclose
	//	*Pos33TicketAction_Miner
	Value                isPos33TicketAction_Value `protobuf_oneof:"value"`
	Ty                   int32                     `protobuf:"varint,10,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Pos33TicketAction) Reset()         { *m = Pos33TicketAction{} }
func (m *Pos33TicketAction) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketAction) ProtoMessage()    {}
func (*Pos33TicketAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{1}
}

func (m *Pos33TicketAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketAction.Unmarshal(m, b)
}
func (m *Pos33TicketAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketAction.Marshal(b, m, deterministic)
}
func (m *Pos33TicketAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketAction.Merge(m, src)
}
func (m *Pos33TicketAction) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketAction.Size(m)
}
func (m *Pos33TicketAction) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketAction.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketAction proto.InternalMessageInfo

type isPos33TicketAction_Value interface {
	isPos33TicketAction_Value()
}

type Pos33TicketAction_Tbind struct {
	Tbind *Pos33TicketBind `protobuf:"bytes,5,opt,name=tbind,proto3,oneof"`
}

type Pos33TicketAction_Topen struct {
	Topen *Pos33TicketOpen `protobuf:"bytes,1,opt,name=topen,proto3,oneof"`
}

type Pos33TicketAction_Genesis struct {
	Genesis *Pos33TicketGenesis `protobuf:"bytes,2,opt,name=genesis,proto3,oneof"`
}

type Pos33TicketAction_Tclose struct {
	Tclose *Pos33TicketClose `protobuf:"bytes,3,opt,name=tclose,proto3,oneof"`
}

type Pos33TicketAction_Miner struct {
	Miner *Pos33TicketMiner `protobuf:"bytes,6,opt,name=miner,proto3,oneof"`
}

func (*Pos33TicketAction_Tbind) isPos33TicketAction_Value() {}

func (*Pos33TicketAction_Topen) isPos33TicketAction_Value() {}

func (*Pos33TicketAction_Genesis) isPos33TicketAction_Value() {}

func (*Pos33TicketAction_Tclose) isPos33TicketAction_Value() {}

func (*Pos33TicketAction_Miner) isPos33TicketAction_Value() {}

func (m *Pos33TicketAction) GetValue() isPos33TicketAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Pos33TicketAction) GetTbind() *Pos33TicketBind {
	if x, ok := m.GetValue().(*Pos33TicketAction_Tbind); ok {
		return x.Tbind
	}
	return nil
}

func (m *Pos33TicketAction) GetTopen() *Pos33TicketOpen {
	if x, ok := m.GetValue().(*Pos33TicketAction_Topen); ok {
		return x.Topen
	}
	return nil
}

func (m *Pos33TicketAction) GetGenesis() *Pos33TicketGenesis {
	if x, ok := m.GetValue().(*Pos33TicketAction_Genesis); ok {
		return x.Genesis
	}
	return nil
}

func (m *Pos33TicketAction) GetTclose() *Pos33TicketClose {
	if x, ok := m.GetValue().(*Pos33TicketAction_Tclose); ok {
		return x.Tclose
	}
	return nil
}

func (m *Pos33TicketAction) GetMiner() *Pos33TicketMiner {
	if x, ok := m.GetValue().(*Pos33TicketAction_Miner); ok {
		return x.Miner
	}
	return nil
}

func (m *Pos33TicketAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Pos33TicketAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Pos33TicketAction_Tbind)(nil),
		(*Pos33TicketAction_Topen)(nil),
		(*Pos33TicketAction_Genesis)(nil),
		(*Pos33TicketAction_Tclose)(nil),
		(*Pos33TicketAction_Miner)(nil),
	}
}

type Pos33Msg struct {
	Data                 []byte      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Ty                   Pos33Msg_Ty `protobuf:"varint,2,opt,name=ty,proto3,enum=types.Pos33Msg_Ty" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Pos33Msg) Reset()         { *m = Pos33Msg{} }
func (m *Pos33Msg) String() string { return proto.CompactTextString(m) }
func (*Pos33Msg) ProtoMessage()    {}
func (*Pos33Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{2}
}

func (m *Pos33Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33Msg.Unmarshal(m, b)
}
func (m *Pos33Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33Msg.Marshal(b, m, deterministic)
}
func (m *Pos33Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33Msg.Merge(m, src)
}
func (m *Pos33Msg) XXX_Size() int {
	return xxx_messageInfo_Pos33Msg.Size(m)
}
func (m *Pos33Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33Msg proto.InternalMessageInfo

func (m *Pos33Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Pos33Msg) GetTy() Pos33Msg_Ty {
	if m != nil {
		return m.Ty
	}
	return Pos33Msg_MV
}

type SortHash struct {
	// string tid = 1;
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortHash) Reset()         { *m = SortHash{} }
func (m *SortHash) String() string { return proto.CompactTextString(m) }
func (*SortHash) ProtoMessage()    {}
func (*SortHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{3}
}

func (m *SortHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortHash.Unmarshal(m, b)
}
func (m *SortHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortHash.Marshal(b, m, deterministic)
}
func (m *SortHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortHash.Merge(m, src)
}
func (m *SortHash) XXX_Size() int {
	return xxx_messageInfo_SortHash.Size(m)
}
func (m *SortHash) XXX_DiscardUnknown() {
	xxx_messageInfo_SortHash.DiscardUnknown(m)
}

var xxx_messageInfo_SortHash proto.InternalMessageInfo

func (m *SortHash) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SortHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SortHash) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SortHash) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type VrfInput struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Ty                   int32    `protobuf:"varint,3,opt,name=ty,proto3" json:"ty,omitempty"`
	Seed                 []byte   `protobuf:"bytes,4,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VrfInput) Reset()         { *m = VrfInput{} }
func (m *VrfInput) String() string { return proto.CompactTextString(m) }
func (*VrfInput) ProtoMessage()    {}
func (*VrfInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{4}
}

func (m *VrfInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrfInput.Unmarshal(m, b)
}
func (m *VrfInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrfInput.Marshal(b, m, deterministic)
}
func (m *VrfInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrfInput.Merge(m, src)
}
func (m *VrfInput) XXX_Size() int {
	return xxx_messageInfo_VrfInput.Size(m)
}
func (m *VrfInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VrfInput.DiscardUnknown(m)
}

var xxx_messageInfo_VrfInput proto.InternalMessageInfo

func (m *VrfInput) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VrfInput) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *VrfInput) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

func (m *VrfInput) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type HashProof struct {
	Input *VrfInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// double diff = 2;
	VrfHash              []byte   `protobuf:"bytes,5,opt,name=vrf_hash,json=vrfHash,proto3" json:"vrf_hash,omitempty"`
	VrfProof             []byte   `protobuf:"bytes,6,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,7,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashProof) Reset()         { *m = HashProof{} }
func (m *HashProof) String() string { return proto.CompactTextString(m) }
func (*HashProof) ProtoMessage()    {}
func (*HashProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{5}
}

func (m *HashProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashProof.Unmarshal(m, b)
}
func (m *HashProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashProof.Marshal(b, m, deterministic)
}
func (m *HashProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashProof.Merge(m, src)
}
func (m *HashProof) XXX_Size() int {
	return xxx_messageInfo_HashProof.Size(m)
}
func (m *HashProof) XXX_DiscardUnknown() {
	xxx_messageInfo_HashProof.DiscardUnknown(m)
}

var xxx_messageInfo_HashProof proto.InternalMessageInfo

func (m *HashProof) GetInput() *VrfInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *HashProof) GetVrfHash() []byte {
	if m != nil {
		return m.VrfHash
	}
	return nil
}

func (m *HashProof) GetVrfProof() []byte {
	if m != nil {
		return m.VrfProof
	}
	return nil
}

func (m *HashProof) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type Pos33SortMsg struct {
	SortHash             *SortHash  `protobuf:"bytes,1,opt,name=sort_hash,json=sortHash,proto3" json:"sort_hash,omitempty"`
	Proof                *HashProof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pos33SortMsg) Reset()         { *m = Pos33SortMsg{} }
func (m *Pos33SortMsg) String() string { return proto.CompactTextString(m) }
func (*Pos33SortMsg) ProtoMessage()    {}
func (*Pos33SortMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{6}
}

func (m *Pos33SortMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33SortMsg.Unmarshal(m, b)
}
func (m *Pos33SortMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33SortMsg.Marshal(b, m, deterministic)
}
func (m *Pos33SortMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33SortMsg.Merge(m, src)
}
func (m *Pos33SortMsg) XXX_Size() int {
	return xxx_messageInfo_Pos33SortMsg.Size(m)
}
func (m *Pos33SortMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33SortMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33SortMsg proto.InternalMessageInfo

func (m *Pos33SortMsg) GetSortHash() *SortHash {
	if m != nil {
		return m.SortHash
	}
	return nil
}

func (m *Pos33SortMsg) GetProof() *HashProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type Pos33Sorts struct {
	Sorts                []*Pos33SortMsg `protobuf:"bytes,1,rep,name=sorts,proto3" json:"sorts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Pos33Sorts) Reset()         { *m = Pos33Sorts{} }
func (m *Pos33Sorts) String() string { return proto.CompactTextString(m) }
func (*Pos33Sorts) ProtoMessage()    {}
func (*Pos33Sorts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{7}
}

func (m *Pos33Sorts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33Sorts.Unmarshal(m, b)
}
func (m *Pos33Sorts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33Sorts.Marshal(b, m, deterministic)
}
func (m *Pos33Sorts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33Sorts.Merge(m, src)
}
func (m *Pos33Sorts) XXX_Size() int {
	return xxx_messageInfo_Pos33Sorts.Size(m)
}
func (m *Pos33Sorts) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33Sorts.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33Sorts proto.InternalMessageInfo

func (m *Pos33Sorts) GetSorts() []*Pos33SortMsg {
	if m != nil {
		return m.Sorts
	}
	return nil
}

type Pos33VoteSorts struct {
	VoteSorts            []*Pos33Sorts `protobuf:"bytes,1,rep,name=vote_sorts,json=voteSorts,proto3" json:"vote_sorts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Pos33VoteSorts) Reset()         { *m = Pos33VoteSorts{} }
func (m *Pos33VoteSorts) String() string { return proto.CompactTextString(m) }
func (*Pos33VoteSorts) ProtoMessage()    {}
func (*Pos33VoteSorts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{8}
}

func (m *Pos33VoteSorts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33VoteSorts.Unmarshal(m, b)
}
func (m *Pos33VoteSorts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33VoteSorts.Marshal(b, m, deterministic)
}
func (m *Pos33VoteSorts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33VoteSorts.Merge(m, src)
}
func (m *Pos33VoteSorts) XXX_Size() int {
	return xxx_messageInfo_Pos33VoteSorts.Size(m)
}
func (m *Pos33VoteSorts) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33VoteSorts.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33VoteSorts proto.InternalMessageInfo

func (m *Pos33VoteSorts) GetVoteSorts() []*Pos33Sorts {
	if m != nil {
		return m.VoteSorts
	}
	return nil
}

type Pos33Online struct {
	Onlined              bool             `protobuf:"varint,2,opt,name=onlined,proto3" json:"onlined,omitempty"`
	Sig                  *types.Signature `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Pos33Online) Reset()         { *m = Pos33Online{} }
func (m *Pos33Online) String() string { return proto.CompactTextString(m) }
func (*Pos33Online) ProtoMessage()    {}
func (*Pos33Online) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{9}
}

func (m *Pos33Online) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33Online.Unmarshal(m, b)
}
func (m *Pos33Online) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33Online.Marshal(b, m, deterministic)
}
func (m *Pos33Online) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33Online.Merge(m, src)
}
func (m *Pos33Online) XXX_Size() int {
	return xxx_messageInfo_Pos33Online.Size(m)
}
func (m *Pos33Online) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33Online.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33Online proto.InternalMessageInfo

func (m *Pos33Online) GetOnlined() bool {
	if m != nil {
		return m.Onlined
	}
	return false
}

func (m *Pos33Online) GetSig() *types.Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Pos33BlockMsg struct {
	B                    *types.Block `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Pid                  string       `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Pos33BlockMsg) Reset()         { *m = Pos33BlockMsg{} }
func (m *Pos33BlockMsg) String() string { return proto.CompactTextString(m) }
func (*Pos33BlockMsg) ProtoMessage()    {}
func (*Pos33BlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{10}
}

func (m *Pos33BlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33BlockMsg.Unmarshal(m, b)
}
func (m *Pos33BlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33BlockMsg.Marshal(b, m, deterministic)
}
func (m *Pos33BlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33BlockMsg.Merge(m, src)
}
func (m *Pos33BlockMsg) XXX_Size() int {
	return xxx_messageInfo_Pos33BlockMsg.Size(m)
}
func (m *Pos33BlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33BlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33BlockMsg proto.InternalMessageInfo

func (m *Pos33BlockMsg) GetB() *types.Block {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Pos33BlockMsg) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type Pos33BlockMsg2 struct {
	B                    *types.Block    `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Vs                   []*Pos33VoteMsg `protobuf:"bytes,2,rep,name=vs,proto3" json:"vs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Pos33BlockMsg2) Reset()         { *m = Pos33BlockMsg2{} }
func (m *Pos33BlockMsg2) String() string { return proto.CompactTextString(m) }
func (*Pos33BlockMsg2) ProtoMessage()    {}
func (*Pos33BlockMsg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{11}
}

func (m *Pos33BlockMsg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33BlockMsg2.Unmarshal(m, b)
}
func (m *Pos33BlockMsg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33BlockMsg2.Marshal(b, m, deterministic)
}
func (m *Pos33BlockMsg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33BlockMsg2.Merge(m, src)
}
func (m *Pos33BlockMsg2) XXX_Size() int {
	return xxx_messageInfo_Pos33BlockMsg2.Size(m)
}
func (m *Pos33BlockMsg2) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33BlockMsg2.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33BlockMsg2 proto.InternalMessageInfo

func (m *Pos33BlockMsg2) GetB() *types.Block {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Pos33BlockMsg2) GetVs() []*Pos33VoteMsg {
	if m != nil {
		return m.Vs
	}
	return nil
}

type Pos33VoteMsg struct {
	Sort                 *Pos33SortMsg    `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Hash                 []byte           `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Round                int32            `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Sig                  *types.Signature `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Pos33VoteMsg) Reset()         { *m = Pos33VoteMsg{} }
func (m *Pos33VoteMsg) String() string { return proto.CompactTextString(m) }
func (*Pos33VoteMsg) ProtoMessage()    {}
func (*Pos33VoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{12}
}

func (m *Pos33VoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33VoteMsg.Unmarshal(m, b)
}
func (m *Pos33VoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33VoteMsg.Marshal(b, m, deterministic)
}
func (m *Pos33VoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33VoteMsg.Merge(m, src)
}
func (m *Pos33VoteMsg) XXX_Size() int {
	return xxx_messageInfo_Pos33VoteMsg.Size(m)
}
func (m *Pos33VoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33VoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33VoteMsg proto.InternalMessageInfo

func (m *Pos33VoteMsg) GetSort() *Pos33SortMsg {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *Pos33VoteMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Pos33VoteMsg) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Pos33VoteMsg) GetSig() *types.Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Pos33DepositMsg struct {
	Maddr                string   `protobuf:"bytes,1,opt,name=maddr,proto3" json:"maddr,omitempty"`
	Raddr                string   `protobuf:"bytes,4,opt,name=raddr,proto3" json:"raddr,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	PreCount             int64    `protobuf:"varint,5,opt,name=pre_count,json=preCount,proto3" json:"pre_count,omitempty"`
	CloseHeight          int64    `protobuf:"varint,6,opt,name=close_height,json=closeHeight,proto3" json:"close_height,omitempty"`
	Reward               int64    `protobuf:"varint,3,opt,name=reward,proto3" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33DepositMsg) Reset()         { *m = Pos33DepositMsg{} }
func (m *Pos33DepositMsg) String() string { return proto.CompactTextString(m) }
func (*Pos33DepositMsg) ProtoMessage()    {}
func (*Pos33DepositMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{13}
}

func (m *Pos33DepositMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33DepositMsg.Unmarshal(m, b)
}
func (m *Pos33DepositMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33DepositMsg.Marshal(b, m, deterministic)
}
func (m *Pos33DepositMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33DepositMsg.Merge(m, src)
}
func (m *Pos33DepositMsg) XXX_Size() int {
	return xxx_messageInfo_Pos33DepositMsg.Size(m)
}
func (m *Pos33DepositMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33DepositMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33DepositMsg proto.InternalMessageInfo

func (m *Pos33DepositMsg) GetMaddr() string {
	if m != nil {
		return m.Maddr
	}
	return ""
}

func (m *Pos33DepositMsg) GetRaddr() string {
	if m != nil {
		return m.Raddr
	}
	return ""
}

func (m *Pos33DepositMsg) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Pos33DepositMsg) GetPreCount() int64 {
	if m != nil {
		return m.PreCount
	}
	return 0
}

func (m *Pos33DepositMsg) GetCloseHeight() int64 {
	if m != nil {
		return m.CloseHeight
	}
	return 0
}

func (m *Pos33DepositMsg) GetReward() int64 {
	if m != nil {
		return m.Reward
	}
	return 0
}

type Pos33SortsVote struct {
	MySorts              []*Pos33SortMsg  `protobuf:"bytes,1,rep,name=my_sorts,json=mySorts,proto3" json:"my_sorts,omitempty"`
	SelectSorts          [][]byte         `protobuf:"bytes,2,rep,name=select_sorts,json=selectSorts,proto3" json:"select_sorts,omitempty"`
	Height               int64            `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32            `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Sig                  *types.Signature `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Pos33SortsVote) Reset()         { *m = Pos33SortsVote{} }
func (m *Pos33SortsVote) String() string { return proto.CompactTextString(m) }
func (*Pos33SortsVote) ProtoMessage()    {}
func (*Pos33SortsVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{14}
}

func (m *Pos33SortsVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33SortsVote.Unmarshal(m, b)
}
func (m *Pos33SortsVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33SortsVote.Marshal(b, m, deterministic)
}
func (m *Pos33SortsVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33SortsVote.Merge(m, src)
}
func (m *Pos33SortsVote) XXX_Size() int {
	return xxx_messageInfo_Pos33SortsVote.Size(m)
}
func (m *Pos33SortsVote) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33SortsVote.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33SortsVote proto.InternalMessageInfo

func (m *Pos33SortsVote) GetMySorts() []*Pos33SortMsg {
	if m != nil {
		return m.MySorts
	}
	return nil
}

func (m *Pos33SortsVote) GetSelectSorts() [][]byte {
	if m != nil {
		return m.SelectSorts
	}
	return nil
}

func (m *Pos33SortsVote) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Pos33SortsVote) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Pos33SortsVote) GetSig() *types.Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Pos33SortMap struct {
	SortMap              map[string]*Pos33SortMsg `protobuf:"bytes,1,rep,name=sort_map,json=sortMap,proto3" json:"sort_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Pos33SortMap) Reset()         { *m = Pos33SortMap{} }
func (m *Pos33SortMap) String() string { return proto.CompactTextString(m) }
func (*Pos33SortMap) ProtoMessage()    {}
func (*Pos33SortMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{15}
}

func (m *Pos33SortMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33SortMap.Unmarshal(m, b)
}
func (m *Pos33SortMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33SortMap.Marshal(b, m, deterministic)
}
func (m *Pos33SortMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33SortMap.Merge(m, src)
}
func (m *Pos33SortMap) XXX_Size() int {
	return xxx_messageInfo_Pos33SortMap.Size(m)
}
func (m *Pos33SortMap) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33SortMap.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33SortMap proto.InternalMessageInfo

func (m *Pos33SortMap) GetSortMap() map[string]*Pos33SortMsg {
	if m != nil {
		return m.SortMap
	}
	return nil
}

type Pos33Votes struct {
	Vs                   []*Pos33VoteMsg `protobuf:"bytes,1,rep,name=vs,proto3" json:"vs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Pos33Votes) Reset()         { *m = Pos33Votes{} }
func (m *Pos33Votes) String() string { return proto.CompactTextString(m) }
func (*Pos33Votes) ProtoMessage()    {}
func (*Pos33Votes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{16}
}

func (m *Pos33Votes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33Votes.Unmarshal(m, b)
}
func (m *Pos33Votes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33Votes.Marshal(b, m, deterministic)
}
func (m *Pos33Votes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33Votes.Merge(m, src)
}
func (m *Pos33Votes) XXX_Size() int {
	return xxx_messageInfo_Pos33Votes.Size(m)
}
func (m *Pos33Votes) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33Votes.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33Votes proto.InternalMessageInfo

func (m *Pos33Votes) GetVs() []*Pos33VoteMsg {
	if m != nil {
		return m.Vs
	}
	return nil
}

type Pos33MakerVotes struct {
	Mvs                  []*Pos33Votes `protobuf:"bytes,1,rep,name=mvs,proto3" json:"mvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Pos33MakerVotes) Reset()         { *m = Pos33MakerVotes{} }
func (m *Pos33MakerVotes) String() string { return proto.CompactTextString(m) }
func (*Pos33MakerVotes) ProtoMessage()    {}
func (*Pos33MakerVotes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{17}
}

func (m *Pos33MakerVotes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33MakerVotes.Unmarshal(m, b)
}
func (m *Pos33MakerVotes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33MakerVotes.Marshal(b, m, deterministic)
}
func (m *Pos33MakerVotes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33MakerVotes.Merge(m, src)
}
func (m *Pos33MakerVotes) XXX_Size() int {
	return xxx_messageInfo_Pos33MakerVotes.Size(m)
}
func (m *Pos33MakerVotes) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33MakerVotes.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33MakerVotes proto.InternalMessageInfo

func (m *Pos33MakerVotes) GetMvs() []*Pos33Votes {
	if m != nil {
		return m.Mvs
	}
	return nil
}

type Pos33TicketMiner struct {
	Sort                 *Pos33SortMsg   `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Vs                   []*Pos33VoteMsg `protobuf:"bytes,2,rep,name=vs,proto3" json:"vs,omitempty"`
	BlockTime            int64           `protobuf:"varint,4,opt,name=blockTime,proto3" json:"blockTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Pos33TicketMiner) Reset()         { *m = Pos33TicketMiner{} }
func (m *Pos33TicketMiner) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketMiner) ProtoMessage()    {}
func (*Pos33TicketMiner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{18}
}

func (m *Pos33TicketMiner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketMiner.Unmarshal(m, b)
}
func (m *Pos33TicketMiner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketMiner.Marshal(b, m, deterministic)
}
func (m *Pos33TicketMiner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketMiner.Merge(m, src)
}
func (m *Pos33TicketMiner) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketMiner.Size(m)
}
func (m *Pos33TicketMiner) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketMiner.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketMiner proto.InternalMessageInfo

func (m *Pos33TicketMiner) GetSort() *Pos33SortMsg {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *Pos33TicketMiner) GetVs() []*Pos33VoteMsg {
	if m != nil {
		return m.Vs
	}
	return nil
}

func (m *Pos33TicketMiner) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

type Pos33MinerFlag struct {
	Flag                 int32    `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Reserve              int64    `protobuf:"varint,2,opt,name=reserve,proto3" json:"reserve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33MinerFlag) Reset()         { *m = Pos33MinerFlag{} }
func (m *Pos33MinerFlag) String() string { return proto.CompactTextString(m) }
func (*Pos33MinerFlag) ProtoMessage()    {}
func (*Pos33MinerFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{19}
}

func (m *Pos33MinerFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33MinerFlag.Unmarshal(m, b)
}
func (m *Pos33MinerFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33MinerFlag.Marshal(b, m, deterministic)
}
func (m *Pos33MinerFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33MinerFlag.Merge(m, src)
}
func (m *Pos33MinerFlag) XXX_Size() int {
	return xxx_messageInfo_Pos33MinerFlag.Size(m)
}
func (m *Pos33MinerFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33MinerFlag.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33MinerFlag proto.InternalMessageInfo

func (m *Pos33MinerFlag) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *Pos33MinerFlag) GetReserve() int64 {
	if m != nil {
		return m.Reserve
	}
	return 0
}

type Pos33PrivMsg struct {
	Priv                 []byte   `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33PrivMsg) Reset()         { *m = Pos33PrivMsg{} }
func (m *Pos33PrivMsg) String() string { return proto.CompactTextString(m) }
func (*Pos33PrivMsg) ProtoMessage()    {}
func (*Pos33PrivMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{20}
}

func (m *Pos33PrivMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33PrivMsg.Unmarshal(m, b)
}
func (m *Pos33PrivMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33PrivMsg.Marshal(b, m, deterministic)
}
func (m *Pos33PrivMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33PrivMsg.Merge(m, src)
}
func (m *Pos33PrivMsg) XXX_Size() int {
	return xxx_messageInfo_Pos33PrivMsg.Size(m)
}
func (m *Pos33PrivMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33PrivMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33PrivMsg proto.InternalMessageInfo

func (m *Pos33PrivMsg) GetPriv() []byte {
	if m != nil {
		return m.Priv
	}
	return nil
}

type Pos33TicketBind struct {
	MinerAddress         string   `protobuf:"bytes,1,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	ReturnAddress        string   `protobuf:"bytes,2,opt,name=returnAddress,proto3" json:"returnAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33TicketBind) Reset()         { *m = Pos33TicketBind{} }
func (m *Pos33TicketBind) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketBind) ProtoMessage()    {}
func (*Pos33TicketBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{21}
}

func (m *Pos33TicketBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketBind.Unmarshal(m, b)
}
func (m *Pos33TicketBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketBind.Marshal(b, m, deterministic)
}
func (m *Pos33TicketBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketBind.Merge(m, src)
}
func (m *Pos33TicketBind) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketBind.Size(m)
}
func (m *Pos33TicketBind) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketBind.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketBind proto.InternalMessageInfo

func (m *Pos33TicketBind) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *Pos33TicketBind) GetReturnAddress() string {
	if m != nil {
		return m.ReturnAddress
	}
	return ""
}

type Pos33TicketOpen struct {
	//用户挖矿的ticket 地址
	MinerAddress string `protobuf:"bytes,1,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	//购买ticket的数目
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	//币实际存储的地址
	ReturnAddress        string   `protobuf:"bytes,3,opt,name=returnAddress,proto3" json:"returnAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33TicketOpen) Reset()         { *m = Pos33TicketOpen{} }
func (m *Pos33TicketOpen) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketOpen) ProtoMessage()    {}
func (*Pos33TicketOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{22}
}

func (m *Pos33TicketOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketOpen.Unmarshal(m, b)
}
func (m *Pos33TicketOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketOpen.Marshal(b, m, deterministic)
}
func (m *Pos33TicketOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketOpen.Merge(m, src)
}
func (m *Pos33TicketOpen) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketOpen.Size(m)
}
func (m *Pos33TicketOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketOpen.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketOpen proto.InternalMessageInfo

func (m *Pos33TicketOpen) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *Pos33TicketOpen) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Pos33TicketOpen) GetReturnAddress() string {
	if m != nil {
		return m.ReturnAddress
	}
	return ""
}

type Pos33TicketGenesis struct {
	MinerAddress         string   `protobuf:"bytes,1,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	ReturnAddress        string   `protobuf:"bytes,2,opt,name=returnAddress,proto3" json:"returnAddress,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33TicketGenesis) Reset()         { *m = Pos33TicketGenesis{} }
func (m *Pos33TicketGenesis) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketGenesis) ProtoMessage()    {}
func (*Pos33TicketGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{23}
}

func (m *Pos33TicketGenesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketGenesis.Unmarshal(m, b)
}
func (m *Pos33TicketGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketGenesis.Marshal(b, m, deterministic)
}
func (m *Pos33TicketGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketGenesis.Merge(m, src)
}
func (m *Pos33TicketGenesis) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketGenesis.Size(m)
}
func (m *Pos33TicketGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketGenesis proto.InternalMessageInfo

func (m *Pos33TicketGenesis) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *Pos33TicketGenesis) GetReturnAddress() string {
	if m != nil {
		return m.ReturnAddress
	}
	return ""
}

func (m *Pos33TicketGenesis) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Pos33TicketClose struct {
	// repeated string ticketId = 1;
	MinerAddress         string   `protobuf:"bytes,2,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33TicketClose) Reset()         { *m = Pos33TicketClose{} }
func (m *Pos33TicketClose) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketClose) ProtoMessage()    {}
func (*Pos33TicketClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{24}
}

func (m *Pos33TicketClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketClose.Unmarshal(m, b)
}
func (m *Pos33TicketClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketClose.Marshal(b, m, deterministic)
}
func (m *Pos33TicketClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketClose.Merge(m, src)
}
func (m *Pos33TicketClose) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketClose.Size(m)
}
func (m *Pos33TicketClose) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketClose.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketClose proto.InternalMessageInfo

func (m *Pos33TicketClose) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *Pos33TicketClose) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Pos33TicketReward struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33TicketReward) Reset()         { *m = Pos33TicketReward{} }
func (m *Pos33TicketReward) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketReward) ProtoMessage()    {}
func (*Pos33TicketReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{25}
}

func (m *Pos33TicketReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketReward.Unmarshal(m, b)
}
func (m *Pos33TicketReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketReward.Marshal(b, m, deterministic)
}
func (m *Pos33TicketReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketReward.Merge(m, src)
}
func (m *Pos33TicketReward) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketReward.Size(m)
}
func (m *Pos33TicketReward) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketReward.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketReward proto.InternalMessageInfo

func (m *Pos33TicketReward) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Pos33TicketReward) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Pos33TicketList struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos33TicketList) Reset()         { *m = Pos33TicketList{} }
func (m *Pos33TicketList) String() string { return proto.CompactTextString(m) }
func (*Pos33TicketList) ProtoMessage()    {}
func (*Pos33TicketList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{26}
}

func (m *Pos33TicketList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos33TicketList.Unmarshal(m, b)
}
func (m *Pos33TicketList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos33TicketList.Marshal(b, m, deterministic)
}
func (m *Pos33TicketList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos33TicketList.Merge(m, src)
}
func (m *Pos33TicketList) XXX_Size() int {
	return xxx_messageInfo_Pos33TicketList.Size(m)
}
func (m *Pos33TicketList) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos33TicketList.DiscardUnknown(m)
}

var xxx_messageInfo_Pos33TicketList proto.InternalMessageInfo

func (m *Pos33TicketList) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Pos33TicketList) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReplyPos33TicketReward struct {
	VoterReward          int64    `protobuf:"varint,1,opt,name=voter_reward,json=voterReward,proto3" json:"voter_reward,omitempty"`
	MinerReward          int64    `protobuf:"varint,2,opt,name=miner_reward,json=minerReward,proto3" json:"miner_reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyPos33TicketReward) Reset()         { *m = ReplyPos33TicketReward{} }
func (m *ReplyPos33TicketReward) String() string { return proto.CompactTextString(m) }
func (*ReplyPos33TicketReward) ProtoMessage()    {}
func (*ReplyPos33TicketReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{27}
}

func (m *ReplyPos33TicketReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPos33TicketReward.Unmarshal(m, b)
}
func (m *ReplyPos33TicketReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPos33TicketReward.Marshal(b, m, deterministic)
}
func (m *ReplyPos33TicketReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPos33TicketReward.Merge(m, src)
}
func (m *ReplyPos33TicketReward) XXX_Size() int {
	return xxx_messageInfo_ReplyPos33TicketReward.Size(m)
}
func (m *ReplyPos33TicketReward) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPos33TicketReward.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPos33TicketReward proto.InternalMessageInfo

func (m *ReplyPos33TicketReward) GetVoterReward() int64 {
	if m != nil {
		return m.VoterReward
	}
	return 0
}

func (m *ReplyPos33TicketReward) GetMinerReward() int64 {
	if m != nil {
		return m.MinerReward
	}
	return 0
}

type ReplyWalletPos33Count struct {
	Privkey              []byte   `protobuf:"bytes,2,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyWalletPos33Count) Reset()         { *m = ReplyWalletPos33Count{} }
func (m *ReplyWalletPos33Count) String() string { return proto.CompactTextString(m) }
func (*ReplyWalletPos33Count) ProtoMessage()    {}
func (*ReplyWalletPos33Count) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{28}
}

func (m *ReplyWalletPos33Count) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyWalletPos33Count.Unmarshal(m, b)
}
func (m *ReplyWalletPos33Count) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyWalletPos33Count.Marshal(b, m, deterministic)
}
func (m *ReplyWalletPos33Count) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyWalletPos33Count.Merge(m, src)
}
func (m *ReplyWalletPos33Count) XXX_Size() int {
	return xxx_messageInfo_ReplyWalletPos33Count.Size(m)
}
func (m *ReplyWalletPos33Count) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyWalletPos33Count.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyWalletPos33Count proto.InternalMessageInfo

func (m *ReplyWalletPos33Count) GetPrivkey() []byte {
	if m != nil {
		return m.Privkey
	}
	return nil
}

func (m *ReplyWalletPos33Count) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReceiptPos33Deposit struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptPos33Deposit) Reset()         { *m = ReceiptPos33Deposit{} }
func (m *ReceiptPos33Deposit) String() string { return proto.CompactTextString(m) }
func (*ReceiptPos33Deposit) ProtoMessage()    {}
func (*ReceiptPos33Deposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{29}
}

func (m *ReceiptPos33Deposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptPos33Deposit.Unmarshal(m, b)
}
func (m *ReceiptPos33Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptPos33Deposit.Marshal(b, m, deterministic)
}
func (m *ReceiptPos33Deposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptPos33Deposit.Merge(m, src)
}
func (m *ReceiptPos33Deposit) XXX_Size() int {
	return xxx_messageInfo_ReceiptPos33Deposit.Size(m)
}
func (m *ReceiptPos33Deposit) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptPos33Deposit.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptPos33Deposit proto.InternalMessageInfo

func (m *ReceiptPos33Deposit) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptPos33Deposit) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReceiptPos33Miner struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Reward               int64    `protobuf:"varint,3,opt,name=reward,proto3" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptPos33Miner) Reset()         { *m = ReceiptPos33Miner{} }
func (m *ReceiptPos33Miner) String() string { return proto.CompactTextString(m) }
func (*ReceiptPos33Miner) ProtoMessage()    {}
func (*ReceiptPos33Miner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d3cfebaf15bc9b, []int{30}
}

func (m *ReceiptPos33Miner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptPos33Miner.Unmarshal(m, b)
}
func (m *ReceiptPos33Miner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptPos33Miner.Marshal(b, m, deterministic)
}
func (m *ReceiptPos33Miner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptPos33Miner.Merge(m, src)
}
func (m *ReceiptPos33Miner) XXX_Size() int {
	return xxx_messageInfo_ReceiptPos33Miner.Size(m)
}
func (m *ReceiptPos33Miner) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptPos33Miner.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptPos33Miner proto.InternalMessageInfo

func (m *ReceiptPos33Miner) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptPos33Miner) GetReward() int64 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func init() {
	proto.RegisterEnum("types.Pos33Msg_Ty", Pos33Msg_Ty_name, Pos33Msg_Ty_value)
	proto.RegisterType((*Pos33Ticket)(nil), "types.Pos33Ticket")
	proto.RegisterType((*Pos33TicketAction)(nil), "types.Pos33TicketAction")
	proto.RegisterType((*Pos33Msg)(nil), "types.Pos33Msg")
	proto.RegisterType((*SortHash)(nil), "types.SortHash")
	proto.RegisterType((*VrfInput)(nil), "types.VrfInput")
	proto.RegisterType((*HashProof)(nil), "types.HashProof")
	proto.RegisterType((*Pos33SortMsg)(nil), "types.Pos33SortMsg")
	proto.RegisterType((*Pos33Sorts)(nil), "types.Pos33Sorts")
	proto.RegisterType((*Pos33VoteSorts)(nil), "types.Pos33VoteSorts")
	proto.RegisterType((*Pos33Online)(nil), "types.Pos33Online")
	proto.RegisterType((*Pos33BlockMsg)(nil), "types.Pos33BlockMsg")
	proto.RegisterType((*Pos33BlockMsg2)(nil), "types.Pos33BlockMsg2")
	proto.RegisterType((*Pos33VoteMsg)(nil), "types.Pos33VoteMsg")
	proto.RegisterType((*Pos33DepositMsg)(nil), "types.Pos33DepositMsg")
	proto.RegisterType((*Pos33SortsVote)(nil), "types.Pos33SortsVote")
	proto.RegisterType((*Pos33SortMap)(nil), "types.Pos33SortMap")
	proto.RegisterMapType((map[string]*Pos33SortMsg)(nil), "types.Pos33SortMap.SortMapEntry")
	proto.RegisterType((*Pos33Votes)(nil), "types.Pos33Votes")
	proto.RegisterType((*Pos33MakerVotes)(nil), "types.Pos33MakerVotes")
	proto.RegisterType((*Pos33TicketMiner)(nil), "types.Pos33TicketMiner")
	proto.RegisterType((*Pos33MinerFlag)(nil), "types.Pos33MinerFlag")
	proto.RegisterType((*Pos33PrivMsg)(nil), "types.Pos33PrivMsg")
	proto.RegisterType((*Pos33TicketBind)(nil), "types.Pos33TicketBind")
	proto.RegisterType((*Pos33TicketOpen)(nil), "types.Pos33TicketOpen")
	proto.RegisterType((*Pos33TicketGenesis)(nil), "types.Pos33TicketGenesis")
	proto.RegisterType((*Pos33TicketClose)(nil), "types.Pos33TicketClose")
	proto.RegisterType((*Pos33TicketReward)(nil), "types.Pos33TicketReward")
	proto.RegisterType((*Pos33TicketList)(nil), "types.Pos33TicketList")
	proto.RegisterType((*ReplyPos33TicketReward)(nil), "types.ReplyPos33TicketReward")
	proto.RegisterType((*ReplyWalletPos33Count)(nil), "types.ReplyWalletPos33Count")
	proto.RegisterType((*ReceiptPos33Deposit)(nil), "types.ReceiptPos33Deposit")
	proto.RegisterType((*ReceiptPos33Miner)(nil), "types.ReceiptPos33Miner")
}

func init() {
	proto.RegisterFile("pos33.proto", fileDescriptor_f8d3cfebaf15bc9b)
}

var fileDescriptor_f8d3cfebaf15bc9b = []byte{
	// 1398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6f, 0x1b, 0xc5,
	0x17, 0xcf, 0xee, 0x66, 0x7d, 0x39, 0xde, 0xb4, 0xce, 0xb4, 0xcd, 0xdf, 0xcd, 0xff, 0xa2, 0x74,
	0xfe, 0x5c, 0x82, 0x84, 0x0c, 0x4d, 0x4a, 0x41, 0xa0, 0x52, 0x35, 0x05, 0x9a, 0x8a, 0x86, 0xb6,
	0x93, 0xc8, 0x48, 0x80, 0xb0, 0x36, 0xf6, 0xc4, 0x59, 0xc5, 0xde, 0xdd, 0xce, 0x8c, 0x5d, 0xfc,
	0xc2, 0x03, 0x12, 0xdf, 0x82, 0x17, 0x9e, 0x78, 0xe0, 0x99, 0xaf, 0xc1, 0x67, 0x42, 0xe7, 0xcc,
	0x6c, 0xbc, 0xae, 0xdd, 0x90, 0x07, 0x9e, 0x76, 0xe6, 0xcc, 0xb9, 0xcd, 0xef, 0x5c, 0xe6, 0x2c,
	0x34, 0xf2, 0x4c, 0xef, 0xee, 0xb6, 0x73, 0x95, 0x99, 0x8c, 0x85, 0x66, 0x9a, 0x4b, 0xbd, 0x19,
	0xf5, 0xb2, 0xd1, 0x28, 0x4b, 0x2d, 0x71, 0x73, 0xdd, 0xa8, 0x38, 0xd5, 0x71, 0xcf, 0x24, 0xe7,
	0xa4, 0xe6, 0xf1, 0x30, 0xeb, 0x9d, 0xf5, 0x4e, 0xe3, 0xc4, 0x51, 0xf8, 0xaf, 0x3e, 0x34, 0x9e,
	0xa1, 0xa6, 0xa3, 0xa4, 0x77, 0x26, 0x0d, 0xdb, 0x84, 0x9a, 0xa1, 0xd5, 0xe3, 0x7e, 0xcb, 0xdb,
	0xf2, 0xb6, 0xeb, 0xe2, 0x7c, 0xcf, 0x36, 0xa0, 0xa2, 0x4d, 0x6c, 0xc6, 0xba, 0xe5, 0x6f, 0x79,
	0xdb, 0xa1, 0x70, 0x3b, 0xf6, 0x1f, 0xa8, 0x27, 0xfa, 0x91, 0x4c, 0xa5, 0x4e, 0x74, 0x2b, 0xd8,
	0xf2, 0xb6, 0x6b, 0x62, 0x46, 0x60, 0xff, 0x03, 0xc8, 0x72, 0x99, 0xee, 0xcb, 0x64, 0x70, 0x6a,
	0x5a, 0xab, 0x5b, 0xde, 0x76, 0x20, 0x4a, 0x14, 0xb6, 0x05, 0x8d, 0xde, 0x30, 0xd3, 0xd2, 0x31,
	0x84, 0xc4, 0x50, 0x26, 0xa1, 0x86, 0x51, 0x92, 0x4a, 0xd5, 0x89, 0x87, 0x63, 0xd9, 0xaa, 0x59,
	0x0d, 0x33, 0x0a, 0xe3, 0x10, 0xd1, 0xee, 0x41, 0xbf, 0xaf, 0xa4, 0xd6, 0xad, 0x0a, 0xf9, 0x3d,
	0x47, 0x63, 0x6f, 0xc0, 0x9a, 0x92, 0x66, 0xac, 0xd2, 0x82, 0xa9, 0x4a, 0x4c, 0xf3, 0x44, 0x76,
	0x1d, 0xc2, 0x5c, 0x25, 0x3d, 0xd9, 0xaa, 0x93, 0x11, 0xbb, 0xe1, 0xbf, 0xf9, 0xb0, 0x5e, 0xc2,
	0xe8, 0x01, 0x21, 0xca, 0xda, 0x10, 0x9a, 0xe3, 0x24, 0xed, 0x93, 0xc7, 0x8d, 0x9d, 0x8d, 0x36,
	0xc5, 0xa0, 0x5d, 0x62, 0xdc, 0x4b, 0xd2, 0xfe, 0xfe, 0x8a, 0xb0, 0x6c, 0xc4, 0x8f, 0xd7, 0x26,
	0x58, 0x97, 0xf2, 0x3f, 0x45, 0x50, 0x90, 0x1f, 0xd9, 0xd8, 0x07, 0x50, 0x1d, 0x38, 0x4c, 0x7d,
	0x92, 0xb8, 0xb9, 0x28, 0xe1, 0x30, 0xde, 0x5f, 0x11, 0x05, 0x2f, 0xbb, 0x0d, 0x15, 0x43, 0xe0,
	0x51, 0x24, 0x1a, 0x3b, 0xff, 0x5a, 0x94, 0x7a, 0x48, 0xd8, 0xae, 0x08, 0xc7, 0xc8, 0xde, 0x83,
	0x90, 0xb0, 0x22, 0xe0, 0x96, 0x4a, 0x1c, 0xe0, 0x31, 0xba, 0x46, 0x7c, 0xec, 0x0a, 0xf8, 0x66,
	0xda, 0x02, 0x4a, 0x02, 0xdf, 0x4c, 0xf7, 0xaa, 0x10, 0x4e, 0x30, 0x12, 0xfc, 0x25, 0xd4, 0x48,
	0xea, 0x40, 0x0f, 0x18, 0x83, 0xd5, 0x7e, 0x6c, 0x62, 0xba, 0x6e, 0x24, 0x68, 0xcd, 0x38, 0x09,
	0xe2, 0x75, 0xae, 0xec, 0xb0, 0xb2, 0x99, 0x03, 0x3d, 0x68, 0x1f, 0x4d, 0x51, 0x19, 0xdf, 0x05,
	0xff, 0x68, 0xca, 0x2a, 0xe0, 0x1f, 0x74, 0x9a, 0x2b, 0xf8, 0xdd, 0xeb, 0x34, 0x3d, 0x16, 0x82,
	0xb7, 0xd7, 0xf4, 0x89, 0x7c, 0xd8, 0x0c, 0xf0, 0xdb, 0x39, 0x6c, 0xae, 0xe2, 0xf7, 0x61, 0xa7,
	0x19, 0xf2, 0x6f, 0xa0, 0x76, 0x98, 0x29, 0xb3, 0x1f, 0xeb, 0x53, 0x0c, 0x62, 0x92, 0xf6, 0xe5,
	0x0f, 0x64, 0x39, 0x10, 0x76, 0x83, 0xee, 0x9c, 0xc6, 0xfa, 0x94, 0x8c, 0x47, 0x82, 0xd6, 0xac,
	0x09, 0x41, 0x3a, 0x1e, 0x11, 0x50, 0xa1, 0xc0, 0x25, 0x72, 0x99, 0x64, 0x24, 0x5d, 0x9a, 0xd2,
	0x9a, 0x7f, 0x07, 0xb5, 0x8e, 0x3a, 0x79, 0x9c, 0xe6, 0x63, 0x83, 0x25, 0x70, 0x6a, 0xf3, 0xd4,
	0x2a, 0x77, 0x3b, 0xb4, 0xa9, 0xb2, 0x71, 0xda, 0x77, 0x95, 0x61, 0x37, 0x0e, 0xa7, 0xa0, 0xc0,
	0x09, 0xb5, 0x6b, 0x29, 0xfb, 0xa4, 0x3d, 0x12, 0xb4, 0xe6, 0x3f, 0x79, 0x50, 0x47, 0xb7, 0x9f,
	0xa9, 0x2c, 0x3b, 0x61, 0x6f, 0xa2, 0xef, 0xf9, 0xd8, 0xb8, 0x24, 0xb9, 0xea, 0x30, 0x2a, 0xec,
	0x0b, 0x7b, 0xca, 0x6e, 0x42, 0x6d, 0xa2, 0x4e, 0xba, 0x74, 0xa1, 0x90, 0x94, 0x55, 0x27, 0xea,
	0x84, 0x6e, 0xff, 0x6f, 0xa8, 0xe3, 0x51, 0x8e, 0xea, 0x28, 0xa0, 0x91, 0x40, 0x5e, 0xab, 0x7e,
	0x03, 0x2a, 0xf9, 0xf8, 0xf8, 0x4c, 0x4e, 0x29, 0xfd, 0x23, 0xe1, 0x76, 0xbc, 0x0f, 0x11, 0x85,
	0x01, 0x31, 0xc4, 0xd8, 0xbd, 0x0b, 0x75, 0x9d, 0x29, 0x63, 0x0d, 0xcc, 0xbb, 0x52, 0xc0, 0x2c,
	0x6a, 0xba, 0x00, 0xfc, 0x2d, 0xac, 0x1a, 0x34, 0x67, 0xf3, 0xb4, 0xe9, 0x38, 0xcf, 0x6f, 0x25,
	0xec, 0x31, 0xff, 0x10, 0xe0, 0xdc, 0x8a, 0x66, 0xef, 0x40, 0x88, 0x1a, 0x74, 0xcb, 0xdb, 0x0a,
	0xb6, 0x1b, 0x3b, 0xd7, 0xca, 0xe9, 0xe0, 0xfc, 0x10, 0x96, 0x83, 0xef, 0xc1, 0x15, 0x22, 0x77,
	0x32, 0x23, 0xad, 0xf0, 0xfb, 0x00, 0x93, 0xcc, 0xc8, 0x6e, 0x59, 0xc3, 0xfa, 0xab, 0x1a, 0xb4,
	0xa8, 0x4f, 0x0a, 0x09, 0xfe, 0xa5, 0xeb, 0x73, 0x4f, 0xd3, 0x61, 0x92, 0x4a, 0xd6, 0x82, 0x6a,
	0x46, 0x2b, 0x1b, 0xb2, 0x9a, 0x28, 0xb6, 0x8c, 0x43, 0x70, 0x98, 0x0c, 0x5c, 0xf5, 0x14, 0x77,
	0x39, 0x4c, 0x06, 0x69, 0x6c, 0xc6, 0x4a, 0x0a, 0x3c, 0xe4, 0xf7, 0x60, 0x8d, 0x94, 0xed, 0x61,
	0x3b, 0x45, 0xc0, 0x36, 0xc1, 0x3b, 0x76, 0x40, 0x45, 0x4e, 0x84, 0xce, 0x84, 0x77, 0x8c, 0x59,
	0x96, 0x27, 0xd6, 0x4c, 0x5d, 0xe0, 0x92, 0x3f, 0x77, 0xf7, 0x29, 0xc4, 0x77, 0x2e, 0x94, 0xff,
	0x3f, 0xf8, 0x13, 0xec, 0x01, 0x0b, 0x28, 0x21, 0x1c, 0x88, 0x92, 0x3f, 0xd1, 0xfc, 0x67, 0xcf,
	0x85, 0xd0, 0x11, 0xd9, 0xdb, 0xb0, 0x8a, 0xe0, 0x38, 0xa5, 0x4b, 0xd1, 0x25, 0x86, 0xa5, 0x85,
	0x71, 0x9e, 0xce, 0xab, 0xe5, 0x74, 0xe6, 0x10, 0xe8, 0x8b, 0x90, 0xd1, 0xc9, 0x80, 0xff, 0xee,
	0xc1, 0x55, 0x32, 0xf2, 0x99, 0xcc, 0x33, 0x9d, 0x50, 0x36, 0x5d, 0x87, 0x70, 0x14, 0xf7, 0xfb,
	0xca, 0x3d, 0x28, 0x76, 0x43, 0x36, 0x88, 0xba, 0x6a, 0xa9, 0xaa, 0xa0, 0xf6, 0xb2, 0x71, 0x6a,
	0xc8, 0x9d, 0x40, 0xd8, 0x0d, 0x26, 0x75, 0xae, 0x64, 0xd7, 0x9e, 0xd8, 0x17, 0xa2, 0x96, 0x2b,
	0xf9, 0x90, 0x0e, 0x6f, 0x41, 0x44, 0x7d, 0xac, 0xeb, 0x2a, 0xb3, 0xb2, 0xf8, 0x82, 0x6c, 0x40,
	0x45, 0xc9, 0x97, 0xb1, 0xea, 0x93, 0xf3, 0x81, 0x70, 0x3b, 0xfe, 0x87, 0xe7, 0x22, 0x41, 0x39,
	0x82, 0xd0, 0xb1, 0x36, 0xd4, 0x46, 0xd3, 0xee, 0xdf, 0x66, 0x66, 0x75, 0x34, 0xb5, 0x99, 0x78,
	0x0b, 0x22, 0x2d, 0x87, 0xb2, 0x67, 0x9c, 0x0c, 0xc6, 0x29, 0x12, 0x0d, 0x4b, 0xb3, 0x2c, 0xb3,
	0xa6, 0x11, 0x2c, 0x6f, 0x1a, 0xcb, 0x50, 0x0e, 0x2f, 0x42, 0xf9, 0x17, 0xaf, 0x5c, 0xb0, 0x71,
	0xce, 0x3e, 0x01, 0x2a, 0xc7, 0xee, 0x28, 0xce, 0x9d, 0xd7, 0x5b, 0x0b, 0x5e, 0xc7, 0x79, 0xdb,
	0x7d, 0x3f, 0x4f, 0x8d, 0x9a, 0x8a, 0xaa, 0xb6, 0xbb, 0xcd, 0xa7, 0x10, 0x95, 0x0f, 0x30, 0x61,
	0xb1, 0x45, 0xd8, 0x68, 0xe1, 0x12, 0x6b, 0x95, 0x1a, 0xbc, 0xab, 0xf0, 0xe5, 0xb5, 0x4a, 0x1c,
	0x1f, 0xfb, 0x1f, 0x79, 0xfc, 0xb6, 0x2b, 0x74, 0x04, 0x54, 0xbb, 0xfc, 0xf5, 0x2e, 0xce, 0xdf,
	0xbb, 0x2e, 0x6d, 0x0e, 0xe2, 0x33, 0xa9, 0x0a, 0xb9, 0x60, 0x34, 0x59, 0x5a, 0xdc, 0x74, 0x2e,
	0xf0, 0x94, 0xff, 0x08, 0xcd, 0x57, 0xdf, 0xa9, 0xcb, 0xa7, 0xfe, 0x65, 0x2a, 0x0b, 0xa7, 0x1b,
	0x9a, 0x9a, 0x8e, 0x66, 0xef, 0xc2, 0x8c, 0xc0, 0x3f, 0x75, 0x09, 0x44, 0x96, 0xbf, 0x18, 0xc6,
	0xf4, 0xee, 0x9d, 0x0c, 0xe3, 0x01, 0x59, 0x0f, 0x05, 0xad, 0xb1, 0xdb, 0x28, 0xa9, 0xa5, 0x9a,
	0x48, 0x97, 0xd7, 0xc5, 0x96, 0x73, 0x17, 0xc8, 0x67, 0x2a, 0x99, 0xb8, 0x57, 0x33, 0x57, 0xc9,
	0xa4, 0x78, 0x35, 0x71, 0xcd, 0xbf, 0x75, 0xd8, 0xcc, 0xa6, 0x8a, 0x85, 0x91, 0xc7, 0xbb, 0xcc,
	0xc8, 0xe3, 0x2f, 0x19, 0x79, 0xf8, 0x8b, 0x39, 0xe5, 0x38, 0x82, 0x5c, 0x4a, 0xf9, 0x5c, 0x9d,
	0x86, 0x45, 0x9d, 0x2e, 0x98, 0x0c, 0x96, 0x99, 0x34, 0xc0, 0x16, 0x67, 0x98, 0x7f, 0xee, 0x4a,
	0x33, 0xdf, 0x82, 0x92, 0x6f, 0xfc, 0xc9, 0x5c, 0xa6, 0xd0, 0x0c, 0xb4, 0x60, 0xd3, 0xbf, 0xe8,
	0xa6, 0x73, 0xda, 0xee, 0xcf, 0x8d, 0x84, 0x82, 0xda, 0x09, 0x06, 0xaf, 0xd4, 0xe7, 0x68, 0x5d,
	0x2a, 0x7e, 0xbf, 0x5c, 0xfc, 0xfc, 0xde, 0x1c, 0xee, 0x4f, 0x12, 0x6d, 0x5e, 0x27, 0xee, 0x66,
	0xee, 0xa0, 0x3c, 0x73, 0xf3, 0xef, 0x61, 0x43, 0xc8, 0x7c, 0x38, 0x5d, 0x74, 0xe2, 0x16, 0x44,
	0xf8, 0xea, 0xa9, 0xae, 0xeb, 0x78, 0x76, 0x50, 0x69, 0x10, 0x6d, 0xc6, 0x42, 0x57, 0x2c, 0x58,
	0xac, 0x67, 0x0d, 0xa2, 0x59, 0x16, 0xfe, 0x08, 0x6e, 0x90, 0xfe, 0xaf, 0xe3, 0xe1, 0x50, 0x1a,
	0xb2, 0x62, 0xbb, 0x6d, 0x0b, 0xaa, 0x98, 0x94, 0xd8, 0x20, 0xec, 0x8b, 0x51, 0x6c, 0x67, 0x40,
	0x79, 0xa5, 0xd6, 0xcd, 0xef, 0xc3, 0x35, 0x21, 0x7b, 0x32, 0xc9, 0x4d, 0xf9, 0x59, 0x58, 0x7a,
	0xd7, 0x39, 0xa4, 0x4b, 0x0a, 0xd6, 0xcb, 0x0a, 0x6c, 0x89, 0xbf, 0x06, 0xaa, 0x65, 0x4d, 0x7e,
	0xe7, 0x4f, 0xcf, 0xfd, 0x2c, 0xb9, 0x5f, 0x9c, 0x3b, 0x70, 0xed, 0x91, 0xbb, 0x92, 0xcb, 0x05,
	0xba, 0xd8, 0x9a, 0x6b, 0x00, 0x42, 0xbe, 0xf8, 0x2a, 0x19, 0x6e, 0x16, 0xcf, 0xf0, 0xe3, 0xd4,
	0xdc, 0xbd, 0xc3, 0x57, 0xd8, 0x5d, 0x58, 0x3b, 0x94, 0xe6, 0xc1, 0xd8, 0x64, 0x07, 0x49, 0x9a,
	0xa4, 0x03, 0x76, 0x63, 0x6e, 0x7e, 0x2d, 0xca, 0xff, 0x5c, 0x8e, 0xd0, 0xe3, 0x2b, 0xec, 0x39,
	0x5c, 0x9f, 0xb7, 0xe6, 0x62, 0xd0, 0x5a, 0x9c, 0xb2, 0xed, 0xc9, 0xe6, 0x7f, 0xcb, 0x1a, 0x16,
	0x8e, 0xf9, 0xca, 0x71, 0x85, 0x7e, 0xdd, 0x76, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x20, 0xd9,
	0x9a, 0x99, 0x03, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// Pos33TicketClient is the client API for Pos33Ticket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Pos33TicketClient interface {
	//创建绑定挖矿
	// rpc CreateBindMiner(ReqBindPos33Miner) returns(ReplyBindPos33Miner) {}
	//查询钱包票数
	GetPos33TicketCount(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*types.Int64, error)
	//设置自动挖矿
	SetAutoMining(ctx context.Context, in *Pos33MinerFlag, opts ...grpc.CallOption) (*types.Reply, error)
	//查询奖励
	GetPos33TicketReward(ctx context.Context, in *Pos33TicketReward, opts ...grpc.CallOption) (*ReplyPos33TicketReward, error)
}

type pos33TicketClient struct {
	cc grpc.ClientConnInterface
}

func NewPos33TicketClient(cc grpc.ClientConnInterface) Pos33TicketClient {
	return &pos33TicketClient{cc}
}

func (c *pos33TicketClient) GetPos33TicketCount(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*types.Int64, error) {
	out := new(types.Int64)
	err := c.cc.Invoke(ctx, "/types.pos33Ticket/GetPos33TicketCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pos33TicketClient) SetAutoMining(ctx context.Context, in *Pos33MinerFlag, opts ...grpc.CallOption) (*types.Reply, error) {
	out := new(types.Reply)
	err := c.cc.Invoke(ctx, "/types.pos33Ticket/SetAutoMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pos33TicketClient) GetPos33TicketReward(ctx context.Context, in *Pos33TicketReward, opts ...grpc.CallOption) (*ReplyPos33TicketReward, error) {
	out := new(ReplyPos33TicketReward)
	err := c.cc.Invoke(ctx, "/types.pos33Ticket/GetPos33TicketReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Pos33TicketServer is the server API for Pos33Ticket service.
type Pos33TicketServer interface {
	//创建绑定挖矿
	// rpc CreateBindMiner(ReqBindPos33Miner) returns(ReplyBindPos33Miner) {}
	//查询钱包票数
	GetPos33TicketCount(context.Context, *types.ReqNil) (*types.Int64, error)
	//设置自动挖矿
	SetAutoMining(context.Context, *Pos33MinerFlag) (*types.Reply, error)
	//查询奖励
	GetPos33TicketReward(context.Context, *Pos33TicketReward) (*ReplyPos33TicketReward, error)
}

// UnimplementedPos33TicketServer can be embedded to have forward compatible implementations.
type UnimplementedPos33TicketServer struct {
}

func (*UnimplementedPos33TicketServer) GetPos33TicketCount(ctx context.Context, req *types.ReqNil) (*types.Int64, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPos33TicketCount not implemented")
}
func (*UnimplementedPos33TicketServer) SetAutoMining(ctx context.Context, req *Pos33MinerFlag) (*types.Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutoMining not implemented")
}
func (*UnimplementedPos33TicketServer) GetPos33TicketReward(ctx context.Context, req *Pos33TicketReward) (*ReplyPos33TicketReward, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPos33TicketReward not implemented")
}

func RegisterPos33TicketServer(s *grpc.Server, srv Pos33TicketServer) {
	s.RegisterService(&_Pos33Ticket_serviceDesc, srv)
}

func _Pos33Ticket_GetPos33TicketCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pos33TicketServer).GetPos33TicketCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.pos33Ticket/GetPos33TicketCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pos33TicketServer).GetPos33TicketCount(ctx, req.(*types.ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pos33Ticket_SetAutoMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pos33MinerFlag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pos33TicketServer).SetAutoMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.pos33Ticket/SetAutoMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pos33TicketServer).SetAutoMining(ctx, req.(*Pos33MinerFlag))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pos33Ticket_GetPos33TicketReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pos33TicketReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pos33TicketServer).GetPos33TicketReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.pos33Ticket/GetPos33TicketReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pos33TicketServer).GetPos33TicketReward(ctx, req.(*Pos33TicketReward))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pos33Ticket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.pos33Ticket",
	HandlerType: (*Pos33TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPos33TicketCount",
			Handler:    _Pos33Ticket_GetPos33TicketCount_Handler,
		},
		{
			MethodName: "SetAutoMining",
			Handler:    _Pos33Ticket_SetAutoMining_Handler,
		},
		{
			MethodName: "GetPos33TicketReward",
			Handler:    _Pos33Ticket_GetPos33TicketReward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pos33.proto",
}
